apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - issuer.yaml
components:
  - ../../components/promtail
# Uncomment this to enable rate limiting
#  - ../../components/promtail
namespace: nexodus
patches:
  - target:
      kind: Ingress
      name: apiproxy
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.try.nexodus.127.0.0.1.nip.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.try.nexodus.127.0.0.1.nip.io
  - target:
      kind: Ingress
      name: frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: try.nexodus.127.0.0.1.nip.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: try.nexodus.127.0.0.1.nip.io
  - target:
      kind: Ingress
      name: apiproxy
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: nexodus-issuer
  - target:
      kind: Ingress
      name: frontend
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: nexodus-issuer
  - target:
      kind: Deployment
      name: apiproxy
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
  - target:
      kind: Deployment
      name: apiserver
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
  - target:
      kind: Deployment
      name: ipam
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
  - target:
      kind: PostgresCluster
      name: database
    patch: |-
      - op: remove
        path: /spec/instances/0/resources/limits
  - target:
      kind: Deployment
      name: backend-cli
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value: [{"name":"trust","mountPath":"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem","readOnly":true,"subPath":"tls-ca-bundle.pem"}]
      - op: add
        path: /spec/template/spec/volumes
        value: [{"name":"trust","secret":{"secretName":"nexodus-ca-key-pair","optional":false,"items":[{"key":"ca.crt","path":"tls-ca-bundle.pem"}]}}]
  - target:
      kind: Deployment
      name: backend-web
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value: [{"name":"trust","mountPath":"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem","readOnly":true,"subPath":"tls-ca-bundle.pem"}]
      - op: add
        path: /spec/template/spec/volumes
        value: [{"name":"trust","secret":{"secretName":"nexodus-ca-key-pair","optional":false,"items":[{"key":"ca.crt","path":"tls-ca-bundle.pem"}]}}]
  - target:
      kind: Deployment
      name: apiserver
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value: [{"name":"trust","mountPath":"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem","readOnly":true,"subPath":"tls-ca-bundle.pem"}]
      - op: add
        path: /spec/template/spec/volumes
        value: [{"name":"trust","secret":{"secretName":"nexodus-ca-key-pair","optional":false,"items":[{"key":"ca.crt","path":"tls-ca-bundle.pem"}]}}]
